dist: xenial
language: scala
scala:
  - 2.12.8
  - 2.13.1
jdk:
   - oraclejdk11
script:
  - sbt scalafmtSbtCheck scalafmtCheck test:scalafmtCheck
dist: trusty
   - openjdk11
before_install:
 - sudo apt-get update -qq
   #- sudo apt-get install -qq libatlas3gf-base libopenblas-base
sbt_args: -Dcom.github.fommil.netlib.BLAS=com.github.fommil.netlib.F2jBLAS -Dcom.github.fommil.netlib.LAPACK=com.github.fommil.netlib.F2jLAPACK -Dcom.github.fommil.netlib.ARPACK=com.github.fommil.netlib.F2jARPACK
cache:
  directories:
  - $HOME/.ivy2
